### ISSUE TITLE
Wallet Transactions not updating

### ISSUE THREAD

**Issue by jaakko100500** [OrbitalEnterprises/evekit-sync#2]
Hello and Merry Christmas

I'm trying to build a small market application and for that I'm trying to get recent Wallet Transactions from the EveKit Api. My account name is "ohbaby"

Problem is that the url `https://evekit-model.orbital.enterprises//api/ws/v1/common/wallet_transaction?accessKey=XXX&accessCred=XXX` doesn't seem to contain newest Wallet Transactions

If I check my EVE client it says the newest Wallet Transaction occurred today 19:28 (2018-12-21).

`https://evekit-model.orbital.enterprises//api/ws/v1/common/wallet_transaction?accessKey=XXX&accessCred=XXX` says newest Wallet Transaction is from `2018-11-20 03:10:59.000`

Also downloading csv snapshot from EveKit says there are newer transactions available

I tried:
* Refresh my ESI token
* `reverse=true` (returns an empty list)
* `maxresults=1000000` (returns max 1000 Wallet Transactions)

Any idea why the EveKit rest api doesn't return newest transactions? Am I using it incorrectly or is this a bug?

**Comment by jaakko100500** [comment]
Nvm, I think I need to use `contid` to fetch all of the Wallet Transactions

**Comment by deadlybulb** [comment]
Hi!  Sounds like you got things sorted.  Yes you'll need to use contid to page through the results.  Without any other settings and reverse=false, you'll always be iterating from the first transaction EveKit stored for you.  Once you build up enough transactions you'll want to create a more targeted query.  See my notes below.

Here are some additional tips that are not obvious from the documentation:

- contid is always compared to the cid of each item in the result set.
- MAXRESULTS is always <= 1000 to avoid really long queries against the DB.
- with reverse=false, the result set will start with the first element where cid >= contid
- with reverse=true, the result set will start with the first element where cid <= contid.  This is why you got an empty list when you tried that variant, you'll need to set cid to sometime like MAXLONG (e.g. 9,223,372,036,854,775,807) unless you happen to know the max cid of your result set.
- for wallet transactions in particular, it's useful to query results by date range.  You can do this by setting a range query for the "date" field.  I've tried to document this [here](https://evekit-documentation.readthedocs.io/en/latest/overview/api_view.html#point-in-time-and-historical-results) but essentially you specify a JSON fragment like this: "{start: <startmillis>, end: <endmillis>}", then URL encode that into the endpoint call.  For things like this, I find it useful to use the [API browser](https://evekit.orbital.enterprises/#/sapi/model/-1/-1).  This will help you figure out the correct URL encoding for your query (as well as try some queries out).
